### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by dhordiiuk** [yfsong0709/ResGCNv1#1]
Hey! Thanks for your awesome work! Can you please provide a demo with possibility of inferencing on custom skeletons?

**Comment by wwdok** [comment]
I am new to action recognition, i also want to know if this project can take video or webcam as input, then recognize actions within them ?

**Comment by Anirudh257** [comment]
@dhordiiuk, you can check https://github.com/yfsong0709/ResGCNv1/blob/master/src/preprocess/ntu_generator.py and see how the NTU skeleton is being read and processed. Using this, you can prepare your custom dataset and infer the results on them.

**Comment by Anirudh257** [comment]
@wwdok This project is for skeleton-based actions, not RGB videos. You may need to convert the RGB videos into skeleton format.

**Comment by wwdok** [comment]
> @wwdok This project is for skeleton-based actions, not RGB videos. You may need to convert the RGB videos into skeleton format.

Thanks for your reply ! Hope that one day this project will add demo feature. As far i know `lightweight openpose` or `alphapose` is a good choice to use for generating skeleton.

**Comment by captify-dhordiiuk** [comment]
@Anirudh257 Got it, thanks! I'll try it out

**Comment by Anirudh257** [comment]
@wwdok, @captify-dhordiiuk welcome. Openpose seems good. You may need to convert to the format mentioned in the paper: N x C x T x V x M.

**Comment by yfsong0709** [comment]
@wwdok Please see the ST-GCN code for Kinetics dataset. This dataset is extracted by openpose. https://github.com/yysijie/st-gcn
