### ISSUE TITLE
Train PA-ResGCN-N51 on custom dataset

### ISSUE THREAD

**Issue by rd20karim** [yfsong0709/ResGCNv1#10]
Thank's for sharing this project, I want to know what changes we should made to train on our skeleton data with like example 17 joints for action recogniton, in particular how to set the targets (actions) and define sequence length of the sliding window.
For the partAtten i wonder if it also should be modified to define the new set for merged joints in the convolutional graph (5 five parts) ?

Thank's for your answer !

**Comment by Anirudh257** [comment]
@rd20karim You have to change the ordering in the file graph.py https://github.com/yfsong0709/ResGCNv1/blob/master/src/dataset/graph.py to make it equal to a 17 joint ordering. You also have to specify the data to the shape of (3 x 300 x 17 x 2) wherever mentioned in the code.

**Comment by rd20karim** [comment]
@Anirudh257  Thank's, and what about defining the targets, for action recognition  because in the product 3*300*17*2 I dont see where is take an account the target data (classes) , 3 (dimension joint ?) and 300 ? , 2?

**Comment by Anirudh257** [comment]
@rd20karim yes, make the changes to the shape variable in all config files and the **src/dataset/ntu.py**. It should be enough.
