### ISSUE TITLE
how to plot Figure 4 of your paper？

### ISSUE THREAD

**Issue by liqier** [yfsong0709/ResGCNv1#11]
Thanks for your work! Can you tell me how to plot Figure 4 of your paper!
Look forward to your reply.
![image](https://user-images.githubusercontent.com/55725190/119262555-3e8e2880-bc0e-11eb-9a50-69bd96619c90.png)

**Comment by yfsong0709** [comment]
This figure is drawn by the visualizer module in this code. First, you should insure that there are original NTU dataset in your server and the path settings are correct. Then, extract the data for visualization by 'python main.py -c **** -ex'. Finally, visualize NTU skeletons by ’python main.py -c **** -v‘ (and input command '4'). Moreover, 'visualization_sample' and 'visualization_frames' settings in config file determine the drawn sample and frames.
