### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by whf9527** [yfsong0709/ResGCNv1#12]
For config files: 1001 or 1002,  I am trying to trian the modle   by  "python main.py -c 1002 -g 0"
I get the error:
![image](https://user-images.githubusercontent.com/43332051/119300744-dd109d00-bc93-11eb-8de2-497765a198de.png)

RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

how to deal with the problem.

**Comment by Anirudh257** [comment]
You can try running in a different python version. <=3.6

**Comment by whf9527** [comment]
> You can try running in a different python version. <=3.6

According to error, I do not think is caused by python version

**Comment by yfsong0709** [comment]
Maybe something is wrong in num_class setting. Have you ever change the code in ntu_feeder.py or ntu_generator.py? In my server, this code is running correctly. Please check your code related to num_class setting.

**Comment by whf9527** [comment]
> Maybe something is wrong in num_class setting. Have you ever change the code in ntu_feeder.py or ntu_generator.py? In my server, this code is running correctly. Please check your code related to num_class setting.

Thanks, It's right. I didn't get the data set right. 非常感谢，根据你的提示。我从新看了一下，发现使用ntu_generator生成的数据集有问题。
