### ISSUE TITLE
What is the general definition of connect_joint array in ./src/graph.py

### ISSUE THREAD

**Issue by rd20karim** [yfsong0709/ResGCNv1#13]
@yfsong0709 
Thank's for sharing this project

I wonder what is the general definition that we can use to get the connect_joint array for every skeleton format ?
Is this take an account the direction of connected join ?

(file graph.py)

**Comment by Anirudh257** [comment]
@rd20karim I also had the same doubt but I don't think that it plays a role in the code.

**Comment by yfsong0709** [comment]
@rd20karim @Anirudh257 The connect_joint is a set of target joints of a bone, and the source joints are the indices (the bone direction is always towards the center). For example, there is a skeleton with seven joints {0,1,2,3,4,5,6} (0,1 are hands, 2 is spine, 3,4 are left leg, 5,6 are right leg), and the bones are {0-2, 1-2, 3-2, 4-2, 5-3, 6-4} (joint 2 is the center joint), then the connect_joint is [2, 2, 2, 2, 2, 3, 4] (the center joint 2 is connected with itself).

Hope this comment is helpful to you.

**Comment by Anirudh257** [comment]
@yfsong0709 thanks for the clarification. Where does it help in the model though? I couldn't pinpoint to the exact step.

**Comment by yfsong0709** [comment]
@Anirudh257 It helps to calculate the bone input features (seen in 'src/dataset/data_utils.py').

**Comment by Anirudh257** [comment]
Thanks for the clarification @yfsong0709  :)
