### ISSUE TITLE
Questions for code

### ISSUE THREAD

**Issue by ChenHongBo0420** [yfsong0709/ResGCNv1#14]
Thanks for reading my ask.Your job is prefect good and I have some question.
1. In the attentions.py，line 19 ，why the out_channel *len(self.parts)，but in the paper it should be channel like it input in the first conv input.
2. same in attentions.py I am puzzled on the line 30-33 may you teach me how can it work in your paper saying.
非常感谢 老哥 请您不吝赐教

**Comment by ChenHongBo0420** [comment]
3.I read your paper and found inference speed so I want to know how can it be calculated in the code.By the way，the inference speed and the flops what are the difference between with the them？

**Comment by ChenHongBo0420** [comment]
4.In the paper，I think maybe the residual damage some  inference speed ？It is right？

**Comment by yfsong0709** [comment]
Thanks for your attention.

For the first question, Line 19 in attentions.py is corresponding to the five individual FC layers. The implementation in the code is a concatenation of these FC layers, i.e., 5 * FC(C/r, C) = FC(C/r, C*5), and then split the attention maps to five parts (seen as Line 30 and 31, the 'view' and 'split' operations do this).

Second question, Line 30 calculates the attention maps corresponding to five body parts. Line 31 split them and form a list. Line 32 does the element-wise multiplication. And Line 33 concat them together.

Third, speed is calculated by N_test / (T_test * N_gpu), where N_test denotes the number of test samples, T_test denotes the time for a whole test phase, and N_gpu denotes the number of GPUs. This speed indicator is an equivalent substitution of FLOPs, and the speed indicator is more intuitive and more obvious.

Fourth, residual links may hurt the speed very slightly. But if you remove residual links, the model training will be very difficult to converge. Kaiming's tricks are always useful, just follow them.

**Comment by ChenHongBo0420** [comment]
Thank you very much for your answer.
In the third one, does this have nothing to do with the computing power of different models of GPUs? Sorry I am new here.
At fourth I understand what you mean, to train a deeper network, residuals are necessary, thank you again！

**Comment by ChenHongBo0420** [comment]
sorry for another issue .In the attentions.py ,inter_channel = channel // 4 ，I have some confusion

**Comment by yfsong0709** [comment]
In the third one, I do not compute the FLOPs for each model. But in the next version of ResGCN, I calculate the FLOPs by 'thop' package.

In attentions.py, 'inter_channel' is actually 'inner_channel', used to reduce the computational costs, similar with Bottleneck structure.

**Comment by yfsong0709** [comment]
In the third one, I do not compute the FLOPs for each model. But in the next version of ResGCN, I calculate the FLOPs by 'thop' package.

In attentions.py, 'inter_channel' is actually 'inner_channel', used to reduce the computational costs, similar with Bottleneck structure.

**Comment by ChenHongBo0420** [comment]
Thanks a lot !
