### ISSUE TITLE
support Kinetics-400-Skeleton

### ISSUE THREAD

**Issue by wantsjean** [yfsong0709/ResGCNv1#2]
Hello, thanks for you great work!  Would resgcn surpport kinetics-400-skeleton?
https://paperswithcode.com/sota/skeleton-based-action-recognition-on-kinetics

**Comment by yfsong0709** [comment]
@wantsjean It's OK for using ResGCN in kinetics-400-skeleton. In src/dataset/graph.py, I have already defined the graph for Kinetics. As to the feeder for this dataset, you can see https://github.com/yysijie/st-gcn/blob/master/feeder/feeder_kinetics.py for more detials.
