### ISSUE TITLE
Broken pretrained models

### ISSUE THREAD

**Issue by dhordiiuk** [yfsong0709/ResGCNv1#3]
Could you help, please? Seems like your uploaded models are broken
![Screenshot from 2020-11-24 10-07-24](https://user-images.githubusercontent.com/66029292/100065965-1e3b0800-2e3d-11eb-8861-809c3346f158.png)
![Screenshot from 2020-11-24 10-07-58](https://user-images.githubusercontent.com/66029292/100065968-1f6c3500-2e3d-11eb-9515-bdd9f40f9daa.png)

**Comment by yfsong0709** [comment]
Why zip archive? These pretrained models are saved by torch.save() function, thus you should directly load them by torch.load() function, seen as 'src/utils.py' file. Or maybe there are something wrong in pytorch version or python version?
