### ISSUE TITLE
CUDA run time issue

### ISSUE THREAD

**Issue by peter-yys-yoon** [yfsong0709/ResGCNv1#4]
Evaluating on dataset ntu120 works fine but on but it has a cuda error on ntu60. 

How can fix it?

![image](https://user-images.githubusercontent.com/57890654/102576205-5120a500-4138-11eb-9041-146f5600080a.png)

**Comment by Anirudh257** [comment]
Check the devices in the config file and compare it with the number of GPUs you are running on.

**Comment by yfsong0709** [comment]
Sorry, I can't recognize the error with these two report lines, please show me the whole reports. This error, 'device-side assert triggered', is usually caused by the wrong settings in labels, such as starting with 1 instead of 0. Have you ever modified the dataloaders or other label settings?
