### ISSUE TITLE
Incorrect pre-trained models

### ISSUE THREAD

**Issue by Anirudh257** [yfsong0709/ResGCNv1#5]
I am trying to load the weights for the pre-trained models on the **XView** setting present in the config files: **1010** and **1014**.  
When I load the pre-trained weights into the model, I get this error:

![image](https://user-images.githubusercontent.com/16001446/104442785-9317fc00-55bb-11eb-892c-8d29ebd91429.png)

**Comment by yfsong0709** [comment]
X-view benchmark requires preprocessed skeleton data as 2s-AGCN. Please see Section 4.2 in README to generate the preprocessed skeleton data.

**Comment by Anirudh257** [comment]
Okay, @yfsong0709 I will try preparing the preprocessed data and load again. Thanks!
