### ISSUE TITLE
 Do NOT exist data files: /data1/yifan.song/SkeletonPreprocess/ntu/xsub120/train_label.pkl!

### ISSUE THREAD

**Issue by Void-Mohit** [yfsong0709/ResGCNv1#7]
Error: Do NOT exist data files: /data1/yifan.song/SkeletonPreprocess/ntu/xsub120/train_label.pkl!

the error occurs while using config 1015 and if possible please provide guidelines on how to use a pre-trained model.

**Comment by Anirudh257** [comment]
@Void-Mohit You should change the paths manually.

**Comment by yfsong0709** [comment]
@Void-Mohit Please look at README.md, and follow the steps to change your path and then generate the preprocessed data. Finally, you can train or test the model.
Pretrained models should be downloaded from GoogleDrive (address is shown in README), and put them into the './pretrained' folder. Then, the model will load the pretrained model automatically.

@Anirudh257 Thanks for your response.
