### ISSUE TITLE
It seems I cannot just use pretrained model to visualize?

### ISSUE THREAD

**Issue by hokiwood-geek** [yfsong0709/ResGCNv1#8]
python main.py -c 1001 -ex -v
both pretrained model and dataset are OK.
![image](https://user-images.githubusercontent.com/56180349/116021540-fa455200-a67a-11eb-9d7a-2dabe913a82c.png)

**Comment by yfsong0709** [comment]
Em... This problem may be caused by the difference between the versions of my using code and the released code. You'd better train your own model before visualization. Thank you!
